#+build windows
#+vet
package owin

import win32 "core:sys/windows"
import "core:time"

IDT_TIMER1: UINT_PTR : 10001
IDT_TIMER2: UINT_PTR : 10002

IDI_ICON1 :: 101

CS_VREDRAW         :: CS_STYLES(win32.CS_VREDRAW)
CS_HREDRAW         :: CS_STYLES(win32.CS_HREDRAW)
CS_DBLCLKS         :: CS_STYLES(win32.CS_DBLCLKS)
CS_OWNDC           :: CS_STYLES(win32.CS_OWNDC)
CS_CLASSDC         :: CS_STYLES(win32.CS_CLASSDC)
CS_PARENTDC        :: CS_STYLES(win32.CS_PARENTDC)
CS_NOCLOSE         :: CS_STYLES(win32.CS_NOCLOSE)
CS_SAVEBITS        :: CS_STYLES(win32.CS_SAVEBITS)
CS_BYTEALIGNCLIENT :: CS_STYLES(win32.CS_BYTEALIGNCLIENT)
CS_BYTEALIGNWINDOW :: CS_STYLES(win32.CS_BYTEALIGNWINDOW)
CS_GLOBALCLASS     :: CS_STYLES(win32.CS_GLOBALCLASS)
CS_DROPSHADOW      :: CS_STYLES(win32.CS_DROPSHADOW)

WS_BORDER           :: WS_STYLES(win32.WS_BORDER)
WS_CAPTION          :: WS_STYLES(win32.WS_CAPTION)
WS_CHILD            :: WS_STYLES(win32.WS_CHILD)
WS_CHILDWINDOW      :: WS_STYLES(win32.WS_CHILDWINDOW)
WS_CLIPCHILDREN     :: WS_STYLES(win32.WS_CLIPCHILDREN)
WS_CLIPSIBLINGS     :: WS_STYLES(win32.WS_CLIPSIBLINGS)
WS_DISABLED         :: WS_STYLES(win32.WS_DISABLED)
WS_DLGFRAME         :: WS_STYLES(win32.WS_DLGFRAME)
WS_GROUP            :: WS_STYLES(win32.WS_GROUP)
WS_HSCROLL          :: WS_STYLES(win32.WS_HSCROLL)
WS_ICONIC           :: WS_STYLES(win32.WS_ICONIC)
WS_MAXIMIZE         :: WS_STYLES(win32.WS_MAXIMIZE)
WS_MAXIMIZEBOX      :: WS_STYLES(win32.WS_MAXIMIZEBOX)
WS_MINIMIZE         :: WS_STYLES(win32.WS_MINIMIZE)
WS_MINIMIZEBOX      :: WS_STYLES(win32.WS_MINIMIZEBOX)
WS_OVERLAPPED       :: WS_STYLES(win32.WS_OVERLAPPED)
WS_OVERLAPPEDWINDOW :: WS_STYLES(win32.WS_OVERLAPPEDWINDOW)
WS_POPUP            :: WS_STYLES(win32.WS_POPUP)
WS_POPUPWINDOW      :: WS_STYLES(win32.WS_POPUPWINDOW)
WS_SIZEBOX          :: WS_STYLES(win32.WS_SIZEBOX)
WS_SYSMENU          :: WS_STYLES(win32.WS_SYSMENU)
WS_TABSTOP          :: WS_STYLES(win32.WS_TABSTOP)
WS_THICKFRAME       :: WS_STYLES(win32.WS_THICKFRAME)
WS_TILED            :: WS_STYLES(win32.WS_TILED)
WS_TILEDWINDOW      :: WS_STYLES(win32.WS_TILEDWINDOW)
WS_VISIBLE          :: WS_STYLES(win32.WS_VISIBLE)
WS_VSCROLL          :: WS_STYLES(win32.WS_VSCROLL)

WS_EX_ACCEPTFILES         :: WS_EX_STYLES(win32.WS_EX_ACCEPTFILES)
WS_EX_APPWINDOW           :: WS_EX_STYLES(win32.WS_EX_APPWINDOW)
WS_EX_CLIENTEDGE          :: WS_EX_STYLES(win32.WS_EX_CLIENTEDGE)
WS_EX_COMPOSITED          :: WS_EX_STYLES(win32.WS_EX_COMPOSITED)
WS_EX_CONTEXTHELP         :: WS_EX_STYLES(win32.WS_EX_CONTEXTHELP)
WS_EX_CONTROLPARENT       :: WS_EX_STYLES(win32.WS_EX_CONTROLPARENT)
WS_EX_DLGMODALFRAME       :: WS_EX_STYLES(win32.WS_EX_DLGMODALFRAME)
WS_EX_DRAGDETECT          :: WS_EX_STYLES(win32.WS_EX_DRAGDETECT)
WS_EX_LAYERED             :: WS_EX_STYLES(win32.WS_EX_LAYERED)
WS_EX_LAYOUTRTL           :: WS_EX_STYLES(win32.WS_EX_LAYOUTRTL)
WS_EX_LEFT                :: WS_EX_STYLES(win32.WS_EX_LEFT)
WS_EX_LEFTSCROLLBAR       :: WS_EX_STYLES(win32.WS_EX_LEFTSCROLLBAR)
WS_EX_LTRREADING          :: WS_EX_STYLES(win32.WS_EX_LTRREADING)
WS_EX_MDICHILD            :: WS_EX_STYLES(win32.WS_EX_MDICHILD)
WS_EX_NOACTIVATE          :: WS_EX_STYLES(win32.WS_EX_NOACTIVATE)
WS_EX_NOINHERITLAYOUT     :: WS_EX_STYLES(win32.WS_EX_NOINHERITLAYOUT)
WS_EX_NOPARENTNOTIFY      :: WS_EX_STYLES(win32.WS_EX_NOPARENTNOTIFY)
WS_EX_NOREDIRECTIONBITMAP :: WS_EX_STYLES(win32.WS_EX_NOREDIRECTIONBITMAP)
WS_EX_OVERLAPPEDWINDOW    :: WS_EX_STYLES(win32.WS_EX_OVERLAPPEDWINDOW)
WS_EX_PALETTEWINDOW       :: WS_EX_STYLES(win32.WS_EX_PALETTEWINDOW)
WS_EX_RIGHT               :: WS_EX_STYLES(win32.WS_EX_RIGHT)
WS_EX_RIGHTSCROLLBAR      :: WS_EX_STYLES(win32.WS_EX_RIGHTSCROLLBAR)
WS_EX_RTLREADING          :: WS_EX_STYLES(win32.WS_EX_RTLREADING)
WS_EX_STATICEDGE          :: WS_EX_STYLES(win32.WS_EX_STATICEDGE)
WS_EX_TOOLWINDOW          :: WS_EX_STYLES(win32.WS_EX_TOOLWINDOW)
WS_EX_TOPMOST             :: WS_EX_STYLES(win32.WS_EX_TOPMOST)
WS_EX_TRANSPARENT         :: WS_EX_STYLES(win32.WS_EX_TRANSPARENT)
WS_EX_WINDOWEDGE          :: WS_EX_STYLES(win32.WS_EX_WINDOWEDGE)

CW_USEDEFAULT: i32 : win32.CW_USEDEFAULT

DEFAULT_WINDOW_POSITION: int2 : {CW_USEDEFAULT, CW_USEDEFAULT}
DEFAULT_CS_STYLE: CS_STYLES : CS_HREDRAW | CS_VREDRAW | CS_OWNDC
DEFAULT_WS_STYLE: WS_STYLES : WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU
DEFAULT_WS_EX_STYLE: WS_EX_STYLES : WS_EX_OVERLAPPEDWINDOW
DEFAULT_SLEEP :: time.Millisecond * 10

HPEN_NULL :: HPEN(uintptr(win32.PS_NULL))
HBRUSH_NULL :: HBRUSH(uintptr(win32.BS_NULL))

LANGID_NEUTRAL_DEFAULT :: DWORD(win32.SUBLANG_DEFAULT) << 10 | DWORD(win32.LANG_NEUTRAL) & 0x3FF

// SRCCOPY :: win32.SRCCOPY
BI_RGB :: win32.BI_RGB
